name: "Continuous Integration"

on:
  pull_request:

jobs:

  coding-standards:
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@1.5.1"
    with:
      php-version: "8.1"

  phpunit:
    name: "PHPUnit"
    uses: "doctrine/.github/.github/workflows/continuous-integration.yml@1.5.1"
    with:
      php-versions: '["7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]'
      composer-options: '--ignore-platform-req=php+'
